global:
  scrape_interval: 5s # Scrape every 5 seconds for real-time feel

scrape_configs:
  - job_name: 'ecommerce-consumer'
    metrics_path: '/actuator/prometheus' # The Spring Boot endpoint
    static_configs:
      - targets: ['consumer-service:8081'] # Connects to the Docker container name